/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unicam.cs.pa2024.formula1;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Scanner;

/**
 * Classe main che avvia il gioco di Formula1.
 */
public class App {

    public static void main(String[] args) {
        try (Scanner scanner = new Scanner(System.in)) {
            Menu.displayMenu();
            List<String> validOptions = Arrays.asList("CircuitoAperto", "CircuitoAdAnello");
            String trackSelected = Menu.getValidatedInput(scanner, validOptions);
            Track track = TrackLoader.loadTrack(trackSelected + ".txt");
            InputHandler inputHandler = new InputHandler(scanner);

            List<Driver> drivers = new ArrayList<>();
            drivers.add(new Bot("Bot1", new Position(7, 16), 'B'));                         // Inizializza con la posizione di partenza
            drivers.add(new Player("Player1", new Position(10, 16), inputHandler, '1'));    // Aggiunge un giocatore umano
            drivers.add(new Player("Player2", new Position(9, 16), inputHandler, '2'));     // Aggiunge un giocatore umano
            drivers.add(new Player("Player3", new Position(8, 16), inputHandler, '3'));     // Aggiunge un giocatore umano

            track.display(drivers);
            System.out.println("Inzia la gara : Pronti, Partenza, Via!");
            GameEngine gameEngine = new GameEngine(track, drivers);
            gameEngine.startRace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

}
