/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unicam.cs.pa2024.formula1;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Scanner;

/**
 * The main class to start the Formula 1 simulation.
 */
public class App {

    public static void main(String[] args) {
        try (Scanner scanner = new Scanner(System.in)) {
            Menu.displayMenu();
            List<String> validOptions = Arrays.asList("CircuitoAperto", "CircuitoAdAnello");
            String trackSelected = Menu.getValidatedInput(scanner, validOptions);
            Track track = TrackLoader.loadTrack(trackSelected + ".txt");
            InputHandler inputHandler = new InputHandler(scanner);
            List<DriverInterface> driverInterfaces = new ArrayList<>();
            driverInterfaces.add(new Bot("Bot1", new Position(8, 16)));          // Inizializza con la posizione di partenza
            driverInterfaces.add(new Player("Player1", new Position(10, 16), inputHandler));   // Aggiunge un giocatore umano

            GameEngine gameEngine = new GameEngine(track, driverInterfaces);
            gameEngine.startRace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

}
