/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unicam.cs.pa2024.formula1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class AppTest {


}
